name: Replace GA Secret
on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
jobs:
  replace-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out your code
      
      - name: Replace placeholder with secret
        run: |
          sed -i "s/WOW_A_SECRET_PLACEHOLDER/${{ secrets.WOW_A_SECRET }}/g" index.html
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
