name: Replace GA Secret
on:
  push:
    branches: [ main ]
jobs:
  replace-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Replace GA placeholder
        run: |
          sed -i "s/WOW_A_SECRET_PLACEHOLDER/${{ secrets.WOW_A_SECRET }}/g" index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
