name: Replace Web3Forms Key
on:
  push:
    branches: [ main ]
    
permissions:
  contents: write  # This is crucial for pushing to gh-pages

jobs:
  replace-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for deployment

      - name: Replace web3forms key
        env:
          WEB3_KEY: ${{ secrets.WEB3_KEY }}
        run: |
          sed -i "s|__WEB3_KEY__|${WEB3_KEY}|g" index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          keep_files: true
